version: '3'

services:
  postgres:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: graphity_database
    ports:
      - 5432
  mariadb:
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: graphity_database
    ports:
      - 3306
