
const extensions = [
  '.mjs',
  '.js',
  '.jsx',
]

module.exports = {
  env: {
    browser: true,
    es6: true,
    node: true,
  },
  parserOptions: {
    ecmaVersion: 6,
    sourceType: 'module',
  },
  plugins: [
    'import',
    'unicorn',
  ],
  settings: {
    'import/extensions': extensions,
    'import/resolver': {
      node: {
        extensions,
      },
    },
    'import/ignore': [
      'node_modules',
      '\\.(coffee|scss|css|less|hbs|svg|json)$',
    ],
  },
  rules: {
    // Do not remove comments
    // used for comparison.

    // Possible Errors
    // 'for-direction': 'off'
    'getter-return': ['error', { allowImplicit: true }],
    'no-async-promise-executor': 'error',
    // 'no-await-in-loop': 'off',
    'no-compare-neg-zero': 'error',
    'no-cond-assign': 'error',
    'no-console': 'warn',
    'no-constant-condition': ['warn', { checkLoops: false }],
    // 'no-control-regex': 'off',
    'no-debugger': 'warn',
    'no-dupe-args': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-empty': 'error',
    'no-empty-character-class': 'error',
    'no-ex-assign': 'error',
    'no-extra-boolean-cast': 'error',
    'no-extra-parens': ['warn', 'all', { returnAssign: false }],
    'no-extra-semi': 'error',
    // 'no-func-assign': 'off',
    // 'no-inner-declarations': 'off',
    'no-invalid-regexp': 'error',
    'no-irregular-whitespace': 'error',
    'no-misleading-character-class': 'error',
    'no-obj-calls': 'error',
    // 'no-prototype-builtins': 'off',
    // 'no-regex-spaces': 'off',
    'no-sparse-arrays': 'error',
    'no-template-curly-in-string': 'error',
    'no-unexpected-multiline': 'error',
    'no-unreachable': 'warn',
    'no-unsafe-finally': 'error',
    'no-unsafe-negation': 'error',
    'require-atomic-updates': 'error',
    'use-isnan': 'error',
    'valid-typeof': 'error',

    // Best Practices
    // 'accessor-pairs': 'off',
    'array-callback-return': ['error', { allowImplicit: true }],
    'block-scoped-var': 'error',
    // 'class-methods-use-this': 'off',
    'complexity': 'warn',
    // 'consistent-return': 'off',
    'curly': 'error',
    // 'default-case': 'off',
    'dot-location': ['error', 'property'],
    'dot-notation': ['error', { allowPattern: '_' }],
    'eqeqeq': 'warn',
    'guard-for-in': 'warn',
    'max-classes-per-file': 'error',
    // 'no-alert': 'off',
    'no-caller': 'error',
    'no-case-declarations': 'error',
    // 'no-div-regex': 'off',
    'no-else-return': ['error', { allowElseIf: false }],
    'no-empty-function': 'error',
    'no-empty-pattern': 'error',
    'no-eq-null': 'error',
    'no-eval': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-extra-label': 'error',
    'no-fallthrough': 'warn',
    // 'no-floating-decimal': 'off',
    'no-global-assign': 'error',
    // 'no-implicit-coercion': 'off',
    'no-implicit-globals': 'error',
    'no-implied-eval': 'error',
    'no-invalid-this': 'error',
    'no-iterator': 'error',
    // 'no-labels': 'off',
    // 'no-lone-blocks': 'off',
    'no-loop-func': 'error',
    // 'no-magic-numbers': 'off',
    'no-multi-spaces': 'error',
    'no-multi-str': 'error',
    // 'no-new': 'off',
    'no-new-func': 'error',
    'no-new-wrappers': 'error',
    'no-octal': 'error',
    'no-octal-escape': 'error',
    // 'no-param-reassign': 'off',
    // 'no-proto': 'off',
    'no-redeclare': 'error',
    // 'no-restricted-properties': 'off',
    'no-return-assign': 'error',
    'no-return-await': 'warn',
    'no-script-url': 'error',
    'no-self-assign': 'error',
    'no-self-compare': 'error',
    // 'no-sequences': 'off',
    'no-throw-literal': 'error',
    'no-unmodified-loop-condition': 'error',
    // 'no-unused-expressions': 'off',
    'no-unused-labels': 'error',
    'no-useless-call': 'error',
    'no-useless-catch': 'error',
    'no-useless-concat': 'error',
    'no-useless-escape': 'error',
    'no-useless-return': 'error',
    // 'no-void': 'off',
    'no-warning-comments': ['warn', { location: 'anywhere', terms: ['todo', 'fixme', 'deprecated'] }],
    'no-with': 'error',
    // 'prefer-named-capture-group': 'off',
    'prefer-promise-reject-errors': 'error',
    // 'radix': 'off',
    'require-await': 'warn',
    // 'require-unicode-regexp': 'off',
    // 'vars-on-top': 'off',
    'wrap-iife': ['error', 'inside'],
    'yoda': 'error',

    // Strict Mode
    // 'strict': 'off',

    // Variables
    // 'init-declarations': 'off', // conflict with no-undef-init
    'no-delete-var': 'error',
    'no-label-var': 'error',
    'no-restricted-globals': 'error',
    'no-shadow-restricted-names': 'error',
    'no-undef': 'error',
    'no-undef-init': 'error',
    // 'no-undefined': 'off',
    'no-unused-vars': ['warn', { varsIgnorePattern: '^_', argsIgnorePattern: '^_' }],
    // 'no-use-before-define': 'off',

    // Node.js and CommonJS
    // 'callback-return': 'off',
    // 'global-require': 'off',
    // 'handle-callback-err': 'off',
    'no-buffer-constructor': 'error',
    // 'no-mixed-requires': 'off',
    'no-new-require': 'error',
    // 'no-path-concat': 'off',
    // 'no-process-env': 'off',
    // 'no-process-exit': 'off',
    // 'no-restricted-modules': 'off',
    // 'no-sync': 'off',

    // Stylistic Issues
    'array-bracket-newline': ['error', 'consistent'],
    'array-bracket-spacing': 'error',
    // 'array-element-newline': 'off',
    'block-spacing': 'error',
    'brace-style': ['error', '1tbs', { allowSingleLine: true }],
    'camelcase': 'error',
    // 'capitalized-comments': 'off',
    'comma-dangle': ['error', 'always-multiline'],
    'comma-spacing': 'error',
    'comma-style': 'error',
    'computed-property-spacing': 'error',
    // 'consistent-this': 'off',
    'eol-last': 'error',
    'func-call-spacing': 'error',
    // 'func-name-matching': 'off',
    // 'func-names': 'off',
    'func-style': ['error', 'declaration', { allowArrowFunctions: true }],
    'function-paren-newline': ['error', 'multiline-arguments'],
    // 'id-blacklist': 'off',
    // 'id-length': 'off',
    // 'id-match': 'off',
    'implicit-arrow-linebreak': 'error',

    'indent': ['error', 2, { SwitchCase: 1, flatTernaryExpressions: true }],
    'jsx-quotes': 'error',
    'key-spacing': 'error',
    'keyword-spacing': 'error',
    // 'line-comment-position': 'off',
    'linebreak-style': 'error',
    // 'lines-around-comment': 'off',
    // 'lines-between-class-members': 'off',
    // 'max-depth': 'off',
    // 'max-len': 'off',
    // 'max-lines': 'off',
    // 'max-lines-per-function': 'off',
    // 'max-nested-callbacks': 'off',
    // 'max-params': 'off',
    // 'max-statements': 'off',
    // 'max-statements-per-line': 'off',
    // 'multiline-comment-style': 'off',
    // 'multiline-ternary': 'off',
    // 'new-cap': 'off',
    'new-parens': 'error',
    // 'newline-per-chained-call': 'off',
    'no-array-constructor': 'error',
    // 'no-bitwise': 'off',
    // 'no-continue': 'off',
    // 'no-inline-comments': 'off',
    // 'no-lonely-if': 'off',
    // 'no-mixed-operators': 'off',
    // 'no-mixed-spaces-and-tabs': 'off',
    // 'no-multi-assign': 'off',
    'no-multiple-empty-lines': 'error',
    // 'no-negated-condition': 'off',
    // 'no-nested-ternary': 'off',
    'no-new-object': 'error',
    // 'no-plusplus': 'off',
    // 'no-restricted-syntax': 'error', ??
    'no-tabs': 'error',
    // 'no-ternary': 'off',
    'no-trailing-spaces': 'error',
    // 'no-underscore-dangle': 'off',
    'no-unneeded-ternary': 'error',
    'no-whitespace-before-property': 'error',
    'nonblock-statement-body-position': 'error',
    'object-curly-newline': ['error', { consistent: true }],
    'object-curly-spacing': ['error', 'always'],
    'object-property-newline': ['error', { allowAllPropertiesOnSameLine: true }],
    // 'one-var': 'off',
    // 'one-var-declaration-per-line': 'off',
    // 'operator-assignment': 'off',
    'operator-linebreak': ['error', 'before'],
    // 'padded-blocks': 'off',
    // 'padding-line-between-statements': 'off',
    // 'prefer-object-spread': 'off',
    'quote-props': ['error', 'consistent-as-needed'],
    'quotes': ['error', 'single'],
    'semi': ['error', 'never'],
    'semi-spacing': 'error',
    'semi-style': ['error', 'first'],
    // 'sort-keys': 'off',
    // 'sort-vars': 'off',
    'space-before-blocks': 'error',
    'space-before-function-paren': ['error', { anonymous: 'always', named: 'never', asyncArrow: 'always' }],
    'space-in-parens': 'error',
    'space-infix-ops': 'error',
    'space-unary-ops': 'error',
    'spaced-comment': 'error',
    'switch-colon-spacing': 'error',
    'template-tag-spacing': 'error',
    // 'unicode-bom': 'off',
    // 'wrap-regex': 'off',

    // ECMAScript 6
    // 'arrow-body-style': 'off',
    // 'arrow-parens': 'off',
    'arrow-spacing': 'error',
    'constructor-super': 'error',
    'generator-star-spacing': 'error',
    'no-class-assign': 'error',
    // 'no-confusing-arrow': 'off',
    'no-const-assign': 'error',
    'no-dupe-class-members': 'error',
    'no-duplicate-imports': 'error',
    'no-new-symbol': 'error',
    // 'no-restricted-imports': 'off',
    // 'no-this-before-super': 'off',
    'no-useless-computed-key': 'error',
    'no-useless-constructor': 'error',
    'no-useless-rename': 'error',
    'no-var': 'error',
    'object-shorthand': 'error',
    'prefer-arrow-callback': 'error',
    'prefer-const': 'error',
    // 'prefer-destructuring': 'off',
    'prefer-numeric-literals': 'error',
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'error',
    'require-yield': 'error',
    'rest-spread-spacing': 'error',
    // 'sort-imports': 'off',
    'symbol-description': 'error',
    'template-curly-spacing': 'error',
    'yield-star-spacing': ['error', 'before'],

    // Static analysis
    // 'import/no-unresolved': 'off',
    'import/named': 'error',
    // 'import/default': 'off',
    // 'import/namespace': 'off',
    // 'import/no-restricted-paths': 'error',
    'import/no-absolute-path': 'error',
    'import/no-dynamic-require': 'error',
    // 'import/no-internal-modules': 'off',
    // 'import/no-webpack-loader-syntax': 'off',
    'import/no-self-import': 'error',
    // 'import/no-cycle': 'off',
    'import/no-useless-path-segments': 'error',
    // 'import/no-relative-parent-imports': 'off',
    // 'import/no-unused-modules': 'off',

    // Helpful warnings
    'import/export': 'error',
    'import/no-named-as-default': 'error',
    'import/no-named-as-default-member': 'error',
    // 'import/no-deprecated': 'off', // use no-warning-comments
    // 'import/no-extraneous-dependencies': 'off',
    'import/no-mutable-exports': 'error',
    // 'import/no-unused-modules': 'off',

    // Module systems
    // 'import/unambiguous': 'off',
    // 'import/no-commonjs': 'off',
    'import/no-amd': 'error',
    // 'import/no-nodejs-modules': 'off',

    // Style guide
    'import/first': 'error',
    'import/exports-last': 'error',
    'import/no-duplicates': 'error',
    'import/no-namespace': 'error',
    // 'import/extensions': 'off',
    // 'import/order': 'off',
    'import/newline-after-import': 'error',
    // 'import/prefer-default-export': 'off',
    // 'import/max-dependencies': 'off',
    // 'import/no-unassigned-import': 'off',
    'import/no-named-default': 'error',
    // 'import/no-default-export': 'off',
    // 'import/no-named-export': 'off',
    // 'import/no-anonymous-default-export': 'off',
    // 'import/group-exports': 'off',
    // 'import/dynamic-import-chunkname': 'off',

    // Unicorn
    // 'unicorn/catch-error-name': 'off',
    'unicorn/custom-error-definition': 'error',
    'unicorn/error-message': 'error',
    'unicorn/escape-case': 'error',
    'unicorn/explicit-length-check': 'error',
    // 'unicorn/filename-case': 'off',
    'unicorn/import-index': 'error',
    'unicorn/new-for-builtins': 'error',
    // 'unicorn/no-abusive-eslint-disable': 'off',
    'unicorn/no-array-instanceof': 'error',
    'unicorn/no-console-spaces': 'error',
    // 'unicorn/no-fn-reference-in-iterator': 'off',
    'unicorn/no-for-loop': 'error',
    // 'unicorn/no-hex-escape': 'off',
    // 'unicorn/no-keyword-prefix': 'off',
    'unicorn/no-new-buffer': 'error',
    // 'unicorn/no-process-exit': 'error',
    'unicorn/no-unreadable-array-destructuring': 'error',
    'unicorn/no-unsafe-regex': 'error',
    // 'unicorn/no-unused-properties': 'off',
    'unicorn/no-zero-fractions': 'error',
    'unicorn/number-literal-case': 'error',
    'unicorn/prefer-add-event-listener': 'error',
    'unicorn/prefer-event-key': 'error',
    'unicorn/prefer-exponentiation-operator': 'error',
    'unicorn/prefer-flat-map': 'error',
    'unicorn/prefer-includes': 'error',
    'unicorn/prefer-node-append': 'error',
    'unicorn/prefer-node-remove': 'error',
    // 'unicorn/prefer-query-selector': 'off',
    'unicorn/prefer-spread': 'error',
    'unicorn/prefer-starts-ends-with': 'error',
    'unicorn/prefer-text-content': 'error',
    'unicorn/prefer-type-error': 'error',
    // 'unicorn/prevent-abbreviations': 'off',
    'unicorn/regex-shorthand': 'error',
    'unicorn/throw-new-error': 'error',
  },
}
