import { APIGatewayProxyEvent } from 'aws-lambda'

import { eventToHttpRequest } from './event-to-http-request'

const eventSample: APIGatewayProxyEvent = {
  resource: '/',
  path: '/',
  httpMethod: 'GET',
  headers: {
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'ko,en;q=0.9,en-US;q=0.8',
    'cache-control': 'max-age=0',
    'CloudFront-Forwarded-Proto': 'https',
    'CloudFront-Is-Desktop-Viewer': 'true',
    'CloudFront-Is-Mobile-Viewer': 'false',
    'CloudFront-Is-SmartTV-Viewer': 'false',
    'CloudFront-Is-Tablet-Viewer': 'false',
    'CloudFront-Viewer-Country': 'KR',
    'Host': 'graphity.wani.kr',
    'sec-fetch-dest': 'document',
    'sec-fetch-mode': 'navigate',
    'sec-fetch-site': 'none',
    'sec-fetch-user': '?1',
    'upgrade-insecure-requests': '1',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36',
    'Via': '2.0 1234567890.cloudfront.net (CloudFront)',
    'X-Amz-Cf-Id': '########',
    'X-Amzn-Trace-Id': 'Root=1-12345-12345678',
    'X-Forwarded-For': '123.123.123.123, 12.12.12.12',
    'X-Forwarded-Port': '443',
    'X-Forwarded-Proto': 'https',
  },
  multiValueHeaders: {
  },
  queryStringParameters: { hello: 'world' },
  multiValueQueryStringParameters: { hello: ['world'] },
  pathParameters: null,
  stageVariables: null,
  requestContext: {
    authorizer: null,
    resourceId: '########',
    resourcePath: '/',
    httpMethod: 'GET',
    extendedRequestId: '###########',
    requestTime: '11/Apr/2020:00:00:00 +0000',
    path: '/',
    accountId: '123456',
    protocol: 'HTTP/1.1',
    stage: 'dev',
    domainPrefix: 'graphity',
    requestTimeEpoch: 1586611898263,
    requestId: '11111111-1111-1111-1111-111111111111',
    identity: {
      apiKey: null,
      apiKeyId: null,
      cognitoIdentityPoolId: null,
      accountId: null,
      cognitoIdentityId: null,
      caller: null,
      sourceIp: '123.123.123.123',
      principalOrgId: null,
      accessKey: null,
      cognitoAuthenticationType: null,
      cognitoAuthenticationProvider: null,
      userArn: null,
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36',
      user: null,
    },
    domainName: 'graphity.wani.kr',
    apiId: 'abcdefghi',
  },
  body: null,
  isBase64Encoded: false,
}

describe('testsuite of event-to-http-request', () => {
  it('test eventToHttpRequest', () => {
    expect(eventToHttpRequest(eventSample)).toEqual({
      host: 'graphity.wani.kr',
      method: 'GET',
      headers: {
        'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
        'accept-encoding': 'gzip, deflate, br',
        'accept-language': 'ko,en;q=0.9,en-US;q=0.8',
        'cache-control': 'max-age=0',
        'cloudfront-forwarded-proto': 'https',
        'cloudfront-is-desktop-viewer': 'true',
        'cloudfront-is-mobile-viewer': 'false',
        'cloudfront-is-smarttv-viewer': 'false',
        'cloudfront-is-tablet-viewer': 'false',
        'cloudfront-viewer-country': 'KR',
        'host': 'graphity.wani.kr',
        'sec-fetch-dest': 'document',
        'sec-fetch-mode': 'navigate',
        'sec-fetch-site': 'none',
        'sec-fetch-user': '?1',
        'upgrade-insecure-requests': '1',
        'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36',
        'via': '2.0 1234567890.cloudfront.net (CloudFront)',
        'x-amz-cf-id': '########',
        'x-amzn-trace-id': 'Root=1-12345-12345678',
        'x-forwarded-for': '123.123.123.123, 12.12.12.12',
        'x-forwarded-port': '443',
        'x-forwarded-proto': 'https',
      },
      path: '/',
      query: {
        hello: 'world',
      },
    })
  })
})
